version: '3.7'

services:

  app:
    container_name: pokemon_app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: onyx.u-gakugei.ac.jp/pokemon_app
    tty: true
    networks:
      - pokemon-network

  nginx:
    container_name: pokemon_nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    tty: true
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge
